Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\ProgramData\Anaconda3\lib\site-packages\nbclient\client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\ProgramData\Anaconda3\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\ProgramData\Anaconda3\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "C:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\ProgramData\Anaconda3\lib\site-packages\nbclient\client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "C:\ProgramData\Anaconda3\lib\site-packages\nbclient\client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "C:\ProgramData\Anaconda3\lib\site-packages\nbclient\client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import scrapy
import json

class Pta(scrapy.Spider):
    name = "pta"
    file_json = open("url.json")
    start_urls = json.loads(file_json.read())
    urls = []

    for i in range(len(start_urls)):
        b = start_urls[i]['url'][0]
        urls.append(b)
    
    def start_requests(self):
        for url in self.urls:
            yield scrapy.Request(url = url, callback = self.parse)
        
    def parse(self, response):
        

        for jurnal in response.css('#content_journal > ul > li'):
            yield {
                'Judul':data_abstrak.css('div:nth-child(2) > a::text').get(),
                'Penulis':data_abstrak.css('div:nth-child(2) > div:nth-child(2) > span::text').get()[10:],
                'Dosbing_1':data_abstrak.css('div:nth-child(2) > div:nth-child(3) > span::text').get()[21:],
                'Dosbing_2':data_abstrak.css('div:nth-child(2) > div:nth-child(4) > span::text').get()[22:],
                'Abstrak_indo':data_abstrak.css('div:nth-child(4) > div:nth-child(2) > p::text').get(),
            }
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mFileNotFoundError[0m                         Traceback (most recent call last)
[1;32m~\AppData\Local\Temp/ipykernel_13632/1864370129.py[0m in [0;36m<module>[1;34m[0m
[0;32m      2[0m [1;32mimport[0m [0mjson[0m[1;33m[0m[1;33m[0m[0m
[0;32m      3[0m [1;33m[0m[0m
[1;32m----> 4[1;33m [1;32mclass[0m [0mPta[0m[1;33m([0m[0mscrapy[0m[1;33m.[0m[0mSpider[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      5[0m     [0mname[0m [1;33m=[0m [1;34m"pta"[0m[1;33m[0m[1;33m[0m[0m
[0;32m      6[0m     [0mfile_json[0m [1;33m=[0m [0mopen[0m[1;33m([0m[1;34m"url.json"[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\AppData\Local\Temp/ipykernel_13632/1864370129.py[0m in [0;36mPta[1;34m()[0m
[0;32m      4[0m [1;32mclass[0m [0mPta[0m[1;33m([0m[0mscrapy[0m[1;33m.[0m[0mSpider[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m      5[0m     [0mname[0m [1;33m=[0m [1;34m"pta"[0m[1;33m[0m[1;33m[0m[0m
[1;32m----> 6[1;33m     [0mfile_json[0m [1;33m=[0m [0mopen[0m[1;33m([0m[1;34m"url.json"[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      7[0m     [0mstart_urls[0m [1;33m=[0m [0mjson[0m[1;33m.[0m[0mloads[0m[1;33m([0m[0mfile_json[0m[1;33m.[0m[0mread[0m[1;33m([0m[1;33m)[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m      8[0m     [0murls[0m [1;33m=[0m [1;33m[[0m[1;33m][0m[1;33m[0m[1;33m[0m[0m

[1;31mFileNotFoundError[0m: [Errno 2] No such file or directory: 'url.json'
FileNotFoundError: [Errno 2] No such file or directory: 'url.json'

